name = "roadtrip-blackroad"
main = "src/worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
[[routes]]
pattern = "roadtrip.blackroad.io/*"
zone_name = "blackroad.io"
[vars]
ENVIRONMENT = "production"
SERVICE_NAME = "roadtrip"
VERSION = "2.0.0"
[[kv_namespaces]]
binding = "STORE"
id = "e16ec8d299e943d8928311172d4da8f4"
[[d1_databases]]
binding = "DB"
database_name = "blackroad-os-main"
database_id = "e2c6dcd9-c21a-48ac-8807-7b3a6881c4f7"

[[migrations]]
tag = "v2"
deleted_classes = ["ChatRoom"]
